"""optional feature

Revision ID: 38afa1083477
Revises: 95e4ec9bca07
Create Date: 2025-11-20 00:33:44.992389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38afa1083477'
down_revision: Union[str, Sequence[str], None] = '95e4ec9bca07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False))
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'account_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'dietary_pref',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'dietary_restrictions',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'dietary_restrictions',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'dietary_pref',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'account_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
