"""optional password

Revision ID: 670992587939
Revises: 38afa1083477
Create Date: 2025-11-20 00:37:14.409889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '670992587939'
down_revision: Union[str, Sequence[str], None] = '38afa1083477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
