"""extra field added

Revision ID: 95e4ec9bca07
Revises: 8c333aca7da5
Create Date: 2025-11-20 00:28:42.735797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95e4ec9bca07'
down_revision: Union[str, Sequence[str], None] = '8c333aca7da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('user', sa.Column('housing_size', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('budget_pref', sa.Float(), nullable=False))
    op.add_column('user', sa.Column('dietary_pref', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('user', sa.Column('dietary_restrictions', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('user', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.drop_column('user', 'location')
    op.drop_column('user', 'dietary_restrictions')
    op.drop_column('user', 'dietary_pref')
    op.drop_column('user', 'budget_pref')
    op.drop_column('user', 'housing_size')
    op.drop_column('user', 'account_type')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
